### ISSUE TITLE
No support for sharing dashboard views.

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#173]
Dashboards do not allow easy sharing of current filter settings with a simple Share button on the UI or via copy and paste the URL with all the filter settings.

Users are used to being able to share a particular view from apps like Google Maps, Amazon, GitHub, etc.

**Comment by c-w** [comment]
We'll need to serialize all the filter values into the URL on every change and populate the initial filter values from the URL if present. I'd estimate this as 1 developer week of effort.

**Comment by c-w** [comment]
I wonder if it would be possible to use a direct fluxxor/router integration to solve this? E.g. http://fluxxor.com/examples/react-router.html

**Comment by c-w** [comment]
On second thoughts, a direct integration between fluxxor and the router would likely be a fairly involved change. A simpler approach could be to have a separate route that restores the DataStore from state serialized to the URL and an action button that creates a sharing link that contains the required serialized state.

The action button for sharing could be nicely integrated into the new actions toolbar:

![image](https://user-images.githubusercontent.com/1086421/34789353-f5ce97ea-f60b-11e7-8536-7e3680a7ae28.png)

**Comment by c-w** [comment]
We now generate sharing links by on-demand serializing filters as base64-encoded JSON to the URL, e.g.: http://localhost:3000/#/site/Fortis%20Dev/share/eyJmcm9tRGF0ZSI6IjIwMTgtMDEtMDEgMDA6MDA6MDAiLCJ0b0RhdGUiOiIyMDE4LTEyLTMxIDIzOjU5OjU5IiwiZGF0ZXRpbWVTZWxlY3Rpb24iOiIyMDE4IiwidGltZXNwYW5UeXBlIjoieWVhciIsImRhdGFTb3VyY2UiOiJSU1MiLCJtYWludG9waWMiOiJodXJyaWNhbmUiLCJiYm94IjpbMzEuMTM3NjAzMjcwMDIxMjksLTk3LjU5OTc5MjQ4MDQ2ODc2LDI5LjQ5MjIwNjMzNDg0ODcxNCwtOTUuMzY0MDc0NzA3MDMxMjVdLCJ6b29tTGV2ZWwiOjksImNvbmp1bmN0aXZldG9waWNzIjpbXSwiZXh0ZXJuYWxzb3VyY2VpZCI6ImFsbCIsInNlbGVjdGVkcGxhY2UiOnsicGxhY2VpZCI6IiIsIm5hbWUiOiIiLCJwbGFjZWNlbnRyb2lkIjpbXSwicGxhY2ViYm94IjpbXX0sImNhdGVnb3J5IjoiRm9ydGlzIERldiJ9

Here is the deserialized payload that is encoded in the URL above:

![image](https://user-images.githubusercontent.com/1086421/34808977-f5bc0c7a-f65f-11e7-8c9e-22bf8c93f6bb.png)

When the link gets accessed, the site gets rendered with the filters that were serialized into the share URL, here customized data-filter, maintopic, time range, etc.:

![image](https://user-images.githubusercontent.com/1086421/34808865-7f674d46-f65f-11e7-9c46-10ac8c57ea27.png)

The links can get created with the share button:

![image](https://user-images.githubusercontent.com/1086421/34808896-a8e448ea-f65f-11e7-8f15-38fcdf0140e7.png)

**Comment by c-w** [comment]
Ideally I'd love the UI to be more data-driven, i.e., instead of using state and flux for determining what data to query, I'd love to have a fully state-less UI that is driven via the router. So when we switch to a different data source, for example, we're actually linking to a different route which then re-fetches the appropriate data. Nice and clean and functional. However, this would be a much more involved refactor, so it's not worth the investment and risk at this point.
