### ISSUE TITLE
Credentials displayed in clear text

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#175]
Credentials to Microsoft and 3rd party Services (facebook, twitter) are displayed in full in clear text on the admin site

To protect credential leaks, applications obfuscate tokens and credentials in the UI, some times displaying partial credentials, some don't display them at all.
(examples: GitHub, Azure Portal, Amazon, Google Cloud)

**Comment by c-w** [comment]
NB: these credentials are also currently stored in plain text in the Cassandra database and transferred via a non-https connection from the React client to the Node server.

**Comment by c-w** [comment]
The credentials are now hidden in the UI to prevent shoulder surfing.

![image](https://user-images.githubusercontent.com/1086421/33623189-2bbd7dfe-d9be-11e7-9c40-460a4153f069.png)

They're still stored in plain text in the database and transferred over non-https so those issues remain.

**Comment by c-w** [comment]
@xtophs Please let me know if you consider this issue resolved given that your original concern was about the UI, not the credential storage (we should likely spin off the credentials management into a separate issue).

**Comment by c-w** [comment]
Spun out a task for the https task (see above).
