### ISSUE TITLE
Admin pages don't require authentication / authorization

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#176]
Anybody that know the site URL scheme can get admin access site to any fortis site.

**Comment by c-w** [comment]
Marking as critical since this has been called out explicitly as an issue multiple times.

**Comment by c-w** [comment]
Taking this one over. Some notes from conversation with @cicorias:

- Active Directory JS client: https://github.com/cicorias/microsoft-authentication-library-for-js/tree/gov1

- Workflow: login popup -> oauth token in callback -> store it -> pass to every request to node backend https://github.com/cicorias/react-azure-oauth2/blob/dfe7128ae3306473691bd0e56600db4556d795bd/src/components/LoginView.js#L55

- Backend: nodejs -> passport-azure-ad -> https://github.com/cicorias/react-azure-oauth2/blob/dfe7128ae3306473691bd0e56600db4556d795bd/server/server.js#L55

**Comment by c-w** [comment]
Frontend authentication is implemented as of https://github.com/CatalystCode/project-fortis-mono/commit/30b45fba38876fb0b9d922b67ea80d7e35d4e56b

**Comment by c-w** [comment]
Authentication and authorization are now implemented in [project-fortis-mono](https://github.com/CatalystCode/project-fortis-mono).

Authentication is handled via the Azure Active Directory v2 (MSAL) endpoint. The React client requests a token via MSAL and then passes the token to every request to the GraphQL server.

The GraphQL server uses passport to validate the MSAL token and then passes the user's identifier to every resolver. A decorator then checks if the user's identifier is permitted to see the information served by the resolver by checking a users table in Cassandra.

For now there are two roles in the users table: user (view everything) and admin (change settings in the admin panel). At deployment time, the "deploy to Azure" wizard takes as input email identifiers of users that should be set up as admin/users.

To do: add user management to the admin panel.

**Comment by cicorias** [comment]
nice job. thanks. @c-w
