### ISSUE TITLE
Missing Admin Audit capabilities

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#177]
There does not seem to be a capability to see audit logs of modifications.

Would be great for debugging and possible legal reasons if user account and originating IP address for config changes were recorded and audit logs were available.

**Comment by erikschlegel** [comment]
@Smarker can you confirm if this level of auditing is already available in app insights? I believe it is.

**Comment by Smarker** [comment]
We don't have user sessions in place yet, so I did not log user account and originating IP address.

If we get this information, it would be pretty easy to add those two properties. We could add them [here](https://github.com/CatalystCode/project-fortis-services/blob/master/src/clients/appinsights/AppInsightsClient.js#L79-L81) so it's included for all events.

I have logging in place for each of the admin settings, but it only captures:
* number of rows operated on
* operation (query/mutation)
* table operated on
* success or failure of operation

**Comment by c-w** [comment]
This task depends on #176

**Comment by c-w** [comment]
We now log the request user on every GraphQL operation to Application Insights (see yellow highlight in screenshot below):

![image](https://user-images.githubusercontent.com/1086421/34499519-6d830b56-efd4-11e7-9b4d-54bffe205e89.png)

Relevant code: https://github.com/CatalystCode/project-fortis/blob/afa56cf42fc72ecc62b972e6df2db019f554080f/project-fortis-services/src/clients/appinsights/AppInsightsClient.js#L85
