### ISSUE TITLE
Deployment Tool does not display site URL or admin URL

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#180]
Per docs at https://github.com/CatalystCode/project-fortis-pipeline#post-deployment-instructions user is expected to go into the Azure portal, navigate to non-intuitive fields resourcegroup->deployments->[deploymentname] and look up a field called FORTISSITEADMINURL.

1) in most of my attempts, this field is empty
2) step to retrieve the URL is hard to perform even for an IT admin familiar with Azure. Would be great to display that URL on the page that launched the deployment once the deployment finished successfully.

**Comment by c-w** [comment]
The canonical way to solve this would be via [ARM template outputs](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates#outputs).

We already have an outputs section which should include the link to the deployed site:

![image](https://user-images.githubusercontent.com/1086421/32504099-01718c06-c3ad-11e7-8e9f-ebad3f34a619.png)

We are also creating the appropriate tag with the correct URL so that the template can read it back:

![image](https://user-images.githubusercontent.com/1086421/32504263-621e79ce-c3ad-11e7-832b-6bbf8a5f991c.png)

**Comment by erikschlegel** [comment]
I believe @c-w already addressed this in his latest PR. @c-w can you confirm?

**Comment by c-w** [comment]
This is still an issue in the latest deployments.

![image](https://user-images.githubusercontent.com/1086421/33322881-b49fe6b2-d418-11e7-9dc9-c4d40c44195b.png)

We seem to be doing all the right things so maybe it's an issue with ARM and we're limited to one output?

**Comment by c-w** [comment]
Found an example with multiple outputs ([blog](https://blogs.msdn.microsoft.com/girishp/2015/06/16/azure-arm-templatestips-on-using-outputs/)) so this must be an issue with how we're referencing the tags in the output block.

**Comment by c-w** [comment]
This may be due to the tag not existing at the time that the ARM template de-references the outputs section https://stackoverflow.com/a/43819401

**Comment by xtophs** [comment]
The problem may be the IP address in the output, which doesn’t exist by the time the template finishes

Sent from my iPhone

On Nov 28, 2017, at 8:12 AM, Clemens Wolff <notifications@github.com<mailto:notifications@github.com>> wrote:


This may be due to the tag not existing at the time that the ARM template de-references the outputs section https://stackoverflow.com/a/43819401<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fa%2F43819401&data=02%7C01%7Cchristoph%40bracketangles.net%7Cd836e0d27eaf431bbfc308d53669fdce%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636474751210320169&sdata=DH%2BEiV7McxW0Y%2BhBCevlBW5RSj0wifkW6N15Y7KFAfA%3D&reserved=0>

**Comment by c-w** [comment]
Alright, so I think I have a satisfying work-around for this issue. In https://github.com/CatalystCode/project-fortis-pipeline/commit/8564bd50ba1b63d279bacde3cd99efe5fffbdce7 I changed the tagging to be on the resource group level (not on a random one of the ~5 storage accounts used in the deployment). This makes it easier to find the tags. In https://github.com/CatalystCode/project-fortis-pipeline/commit/7448c26908b41578f9e16ad879170f1b898809d7 I then updated the documentation with the post-deployment steps to find the admin site URL which is now just two clicks: first click on "Manage" which opens the resource group and then click on "Tags" to access the deployed site URL.

![image](https://user-images.githubusercontent.com/1086421/33331249-1b1ce1f4-d42f-11e7-8341-0100660e9e74.png)

This work is not directly addressing the issue that our ARM deployment outputs are blank: see previous discussion but I think there's a race condition between the time point at which the ARM template materializes its outputs and the time at which the Azure CLI finishes tagging the resources. Given that the work-around mentioned in this comment actually makes it easier for the user to find the links they need, I'd call this a win overall and stop spending more time on this.

Please re-open if you disagree with this implementation.
