### ISSUE TITLE
Admin site does not display configured event sources

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#182]
Fortis V1 displayed lists of configured facebook and twitter accounts in great detail.

V2 only displays "Twitter" and "Facebook". No details about which accounts are configured on the admin page.

Makes it very hard to verify and troubleshoot for users that don't understand how to query the configuration from the database.

**Comment by c-w** [comment]
I believe this will be implemented by https://github.com/CatalystCode/project-fortis-pipeline/issues/246. Please re-open if you disagree.
