### ISSUE TITLE
Translate Button only available when switching languages

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#184]
Translate capability is great, but very hard to discover.

Consider a non-native speaker using the default configuration of a site. The translate capability is only revealed after switching the UI language.

**Comment by erikschlegel** [comment]
You can only translate news feed items if the event language differs from the selected language. We can do a better job with applying some UX enhancements to help make this functionality clearer.

**Comment by c-w** [comment]
We could always show the button but make it disabled with a popup that indicates when it'll be enabled. This shouldn't take more than a day to implement.

**Comment by c-w** [comment]
Translate button is now always visible but only usable when the item can be meaningfully translated:

![image](https://user-images.githubusercontent.com/1086421/34567927-2a04a646-f132-11e7-9c9e-a1ce27f39cf9.png)
