### ISSUE TITLE
No translate button on the Event Details pop-up

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#185]
The Translate button on the feed widget is great. 

However, to understand the text of  a larger event text, like RSS feed item, users expand the feed item. Unfortunately the pop up with the full item text does not allow for translating the text.

**Comment by c-w** [comment]
Should be easy to implement. 1-2 days of developer effort.

**Comment by c-w** [comment]
Added translation button to the event details popup:

![image](https://user-images.githubusercontent.com/1086421/34571993-1d547654-f13e-11e7-8b93-56c7a7b9da1c.png)

Demonstrating translation in action:

![image](https://user-images.githubusercontent.com/1086421/34572086-6d3a5670-f13e-11e7-9d90-1283d6843f42.png)
