### ISSUE TITLE
Item Pop up does not display images

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#186]
Often, posts and articles include a picture that's very important to understand the item. 

The image is not displayed. Neither is the link to the image clickable. A user has to copy the link, open another browser window and then paste the link to fully understand what an item was about.

**Comment by c-w** [comment]
Images (and other styling like bold/italic/etc.) are now displayed in the event details:

![image](https://user-images.githubusercontent.com/1086421/34576020-9bde5b78-f14a-11e7-9e44-d9399038edc5.png)

The html is being sanitized to remove potential XSS attacks by white-listing specific tags and attributes that may be displayed in the event.
