### ISSUE TITLE
Filters dropdown is confusing

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#188]
Not sure what this dropdown does:
https://files.slack.com/files-pri/T02L6HQ0H-F7U34RUF8/image.png

I don't believe it does what it says, i.e. you don't search FOR a trusted source, term a or location.

I also don't believe the term "trusted source" is still used in the V2 UI

**Comment by erikschlegel** [comment]
Can we have a targeted walkthrough of this issue so I can better understand what isnt properly working?

**Comment by c-w** [comment]
@xtophs Do you think it would make sense for the search box to search over the values in all the dropdown (locations/terms/sources) at the same time? In this way, we remove the need for the user to know in advance what they're looking for and they can simply discover locations/terms/sources as they go along.

**Comment by c-w** [comment]
Unified the dropdown to avoid users having to know about the intricacies of what to search for.

![image](https://user-images.githubusercontent.com/1086421/34783382-728dc98a-f5f9-11e7-8a20-ddb47b157c32.png)
