### ISSUE TITLE
Geo Fence not labelled

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#189]
Maps sometimes display a recognized location as an area on the map:

https://files.slack.com/files-pri/T02L6HQ0H-F7TAQSYH3/image.png

I can't tell where on the UI one finds a description or name of the particular area that's drawn on the map

**Comment by c-w** [comment]
See comment on #190 -- should we just remove the outline?

**Comment by c-w** [comment]
Confusing outline is now removed.
