### ISSUE TITLE
Blue area displaying geofence only in default zoom setting

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#190]
Repro steps:

* Find a number bubble on the map where blue area bounds are displayed, as in https://files.slack.com/files-pri/T02L6HQ0H-F7TAQSYH3/image.png 
* zoom in to the area, with plenty of space around the blue area

Blue area is not redrawn after zooming

**Comment by erikschlegel** [comment]
The cluster area will only display if events occur in multiple places.

**Comment by c-w** [comment]
Should we just remove the outline to avoid user confusion?

**Comment by c-w** [comment]
Confusing outline is now removed.
