### ISSUE TITLE
Sentiment color doesn't match

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#191]
On several occasions I had sentiment colors not match:

* Bubble on map doesn't match color in the item feed  (https://epicstuff.slack.com/files/U4VLP4QBS/F7U3VV1C6/image.png)
* Item feed doesn't match pop up

(can't send repro steps since site currently doesn't load)

**Comment by c-w** [comment]
This is how the newsfeed computes the sentiment color: https://github.com/CatalystCode/project-fortis-interfaces/blob/5eea24b6de37d2b034ba87ec33db8b9e236bfa88/src/components/Insights/FortisEvent.js#L19-L41

This is how the heatmap computes the sentiment color: https://github.com/CatalystCode/project-fortis-interfaces/blob/5eea24b6de37d2b034ba87ec33db8b9e236bfa88/src/components/Insights/Maps/MarkerClusterGroup.js#L79-L96

This is how the details popup computes the sentiment color: https://github.com/CatalystCode/project-fortis-interfaces/blob/5eea24b6de37d2b034ba87ec33db8b9e236bfa88/src/components/Insights/shared.js#L32-L57

The algorithms are out of sync and need to be refactored to use the same logic.

**Comment by c-w** [comment]
The sentiment colors are now consistent across all components:

![image](https://user-images.githubusercontent.com/1086421/34583602-59831ac2-f166-11e7-80f1-3f5f4817759b.png)

![image](https://user-images.githubusercontent.com/1086421/34583613-665aa242-f166-11e7-96ef-182e812acc8d.png)
