### ISSUE TITLE
Other Terms in term filter seems to be wrong

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#192]
Other Terms in the Term Filter widget is checked, but none of the terms underneath is: https://files.slack.com/files-pri/T02L6HQ0H-F7TBFM5GV/image.png

Should Other Terms only be checked when terms below are selected?

**Comment by erikschlegel** [comment]
Both Top 5 and Other Terms options should be removed from the filters section. This is a duplicate issue.

**Comment by c-w** [comment]
Estimate 1 day for removal.

**Comment by c-w** [comment]
The confusing entries are now removed.

![image](https://user-images.githubusercontent.com/1086421/34487777-cc2c167e-efa3-11e7-9111-2170b6d4ae63.png)
