### ISSUE TITLE
No progress indicator or error messages when page starts

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#195]
Page sits at "loading [sitename] watcher..." providing no indication that things are happening. It's confusing over slower connections because the user doesn't know that the site is making progress loading. 
The page also does not display an error when something goes wrong and the page does not load, leaving the user wondering if loading every completes.

**Comment by c-w** [comment]
NB: the error message part of this was implemented in https://github.com/CatalystCode/project-fortis-interfaces/pull/103

**Comment by c-w** [comment]
For the progress indicator, we'll need a counter in the DataStore that tracks how many of the requests necessary to load the dashboard were already processed. The page shown on initial load can then track this counter to provide a loading indicator.

Estimate 1-2 developer days to implement the loading indicator.

**Comment by c-w** [comment]
Loading indicator was implemented in https://github.com/CatalystCode/project-fortis-mono/commit/b8a84e0d3c470a10f911799be972aa27b9c1776b
