### ISSUE TITLE
Timeline widget uses weird start dates

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#196]
Timeline chart used Sat - Sat range for "Last Week" with seemingly arbitrary start and end times. 
The first day of week should come from the users first day of week setting. 
The weird start time may be due to timezone conversions.

**Comment by c-w** [comment]
Unfortunately we can't easily customize the week ranges while keeping efficient queries. We aggregate events to a specific definition of "week" in Spark, store the aggregates in Cassandra, and then display them in the UI. Adding support for alternative week types would unfortunately add too much data overhead in Cassandra.

Resolving this as by-design.
