### ISSUE TITLE
Chart Pop-Up Item Order not in sync with chart

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#197]
Hover over timeline graph
Wait for pop up to come up.
Order of items in the pop up does not reflect order of lines on the chart, which makes it hard to relate the pop up to the chart. https://epicstuff.slack.com/files/U4VLP4QBS/F7UA4DQ79/image.png

Would be great if order of items matched the chart.

**Comment by c-w** [comment]
Order in popup is now the same as lines on graph:

![image](https://user-images.githubusercontent.com/1086421/34489832-bca24d2e-efab-11e7-909b-ec14f417a13d.png)
