### ISSUE TITLE
Translate Button doesn't size properly

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#198]
Translate button renders over text: https://epicstuff.slack.com/files/U4VLP4QBS/F7TBRT89K/image.png

**Comment by c-w** [comment]
The button is now an icon so it doesn't overlap anymore:

![image](https://user-images.githubusercontent.com/1086421/34569388-9fcb8832-f136-11e7-9cee-e19b81e7ccd9.png)
