### ISSUE TITLE
Navigating to "undefined" site shows valid dashboard

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#202]
Navigate to
http://fortis-portal.52.167.224.142.nip.io/#/sites/
Click on Dashboard
http://fortis-portal.52.167.224.142.nip.io/#/site/undefined/

![image](https://user-images.githubusercontent.com/8771377/32494313-c1485d9c-c386-11e7-823d-a38f53477319.png)

**Comment by c-w** [comment]
More generally, we should have a 404 view for undefined routes. Estimate 2-3 days to implement this.

**Comment by c-w** [comment]
Handler for unknown site:

![image](https://user-images.githubusercontent.com/1086421/34537569-ee683c7e-f096-11e7-979e-861de960a0a5.png)

Handler for unknown route:

![image](https://user-images.githubusercontent.com/1086421/34537531-cf5c1ba2-f096-11e7-9add-566ee0699d37.png)
