### ISSUE TITLE
Blue sentiment color in item feed

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#203]
Blue doesn't seem to be used as sentiment color anywhere else:

![image](https://user-images.githubusercontent.com/8771377/32494736-6d9bba02-c388-11e7-94ca-9d277e9bf9d7.png)

**Comment by c-w** [comment]
This has the same root cause as https://github.com/CatalystCode/project-fortis-pipeline/issues/191. Resolving this issue in favor of https://github.com/CatalystCode/project-fortis-pipeline/issues/191.
