### ISSUE TITLE
Time not formatted according to local settings

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#204]
* Hover over timeline
* Wait for pop-up

Time displayed is formatted in ISO format. End users are not very familiar with ISO formatted times. Would be better to read time display format from local settings to also account for customary display in all regions around the world.
 
![image](https://user-images.githubusercontent.com/8771377/32499233-a6317924-c397-11e7-9f74-96da35725536.png)

**Comment by c-w** [comment]
The date in the tooltip is now localized using [moment.js](https://momentjs.com/docs/#localized-formats).

![image](https://user-images.githubusercontent.com/1086421/34532336-d23a2dd6-f083-11e7-8ed0-b38104d9c214.png)
