### ISSUE TITLE
Time axis time formatting not internationalized

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#205]
Label on the time axis formatted for US am/pm time format. Since fortis is targeting international deployments, it would be better to format time according to local settings:

![image](https://user-images.githubusercontent.com/8771377/32499434-2c679988-c398-11e7-8c17-6fb9248ad8d2.png)

**Comment by c-w** [comment]
The label date is now localized using [moment.js](https://momentjs.com/docs/#localized-formats).

![image](https://user-images.githubusercontent.com/1086421/34532917-fd9afa9e-f085-11e7-975d-b668f6339131.png)
