### ISSUE TITLE
Facebook links don't show facebook content

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#208]
Clicking on the link in the item feed or on the Read Original link for facebook posts comes out at a facebook page that the site is not available. 

Maybe get the content from the API instead of redirecting?

![image](https://user-images.githubusercontent.com/8771377/32548982-b3300aaa-c455-11e7-9870-82d3307154c0.png)

**Comment by c-w** [comment]
Here's the code that creates the Facebook post links from the API response:

- posts: https://github.com/CatalystCode/project-fortis/blob/97093adad8eb1c0d0e30f857b2c3fd9cd905c79b/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/analyzer/FacebookPostAnalyzer.scala#L35-L43
- comments: https://github.com/CatalystCode/project-fortis/blob/97093adad8eb1c0d0e30f857b2c3fd9cd905c79b/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/analyzer/FacebookCommentAnalyzer.scala#L22

**Comment by c-w** [comment]
This is blocked on https://github.com/CatalystCode/project-fortis-pipeline/issues/246 and https://github.com/CatalystCode/project-fortis-pipeline/issues/207 so that we can actually configure a site with some Facebook streams and debug this.

**Comment by c-w** [comment]
Removed the non-standard URL generation. Facebook changes the way that they link to content every now and then so we should only rely on officially supported URL generation methods in their API: it's better to not expose a source link in Fortis than to show a link that 404s.
