### ISSUE TITLE
Inconsistent UI: Locations and Terms on item details

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#209]
Locations (left) and search terms (right) are both shown as blue pills, but only locations are highlighted in the text

![image](https://user-images.githubusercontent.com/8771377/32549035-e25d4dd8-c455-11e7-9574-a020d9871b66.png)

**Comment by c-w** [comment]
This is fixed and we highlight both places (shown in red in screenshot below) and keywords (shown in blue in screenshot below):

![image](https://user-images.githubusercontent.com/1086421/34499038-36e2820e-efd2-11e7-983c-ba6b8ba0786a.png)

Relevant code: https://github.com/CatalystCode/project-fortis/blob/97093adad8eb1c0d0e30f857b2c3fd9cd905c79b/project-fortis-interfaces/src/components/dialogs/EventDetails.js#L76-L78
