### ISSUE TITLE
Source selection Formatting in Edge has line breaks

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#214]
Edge (top) breaks lines 
Chrome (bottom) doesn't

![image](https://user-images.githubusercontent.com/8771377/32549729-845f94e0-c458-11e7-8041-61a3e4ff2f82.png)

**Comment by c-w** [comment]
See #213, we should just detect supported browsers (I tested the site in Chrome and Firefox) and alert on non-supported versions.

**Comment by c-w** [comment]
Resolving since as per #213 we'll just support Chrome/Firefox where we know that everything works fine.
