### ISSUE TITLE
Language Change incomplete

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#215]
* open http://fortis-portal.52.167.224.142.nip.io/#/site/armedconflict
* switch language to English

Top 1 search term language does not change in word cloud or Top 5 list. All others change

![image](https://user-images.githubusercontent.com/8771377/32549952-48a7d61e-c459-11e7-829f-78aed1a07490.png)

**Comment by erikschlegel** [comment]
This is a data issue as there isnt a english translation for the spanish term policia. This can be resolved within the admin module.

**Comment by c-w** [comment]
Resolving as per Erik's comment that this is by design.
