### ISSUE TITLE
Language Change does not stick

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#216]
* open http://fortis-portal.52.167.224.142.nip.io/#/site/armedconflict
* change language to en
* refresh page (ctrl-r)

Page is back in spanish

**Comment by erikschlegel** [comment]
Fortis does not support session specific selections. If you refresh your screen all your selections will go back to the page defaults.

**Comment by c-w** [comment]
This can be implemented in the same way as https://github.com/CatalystCode/project-fortis-pipeline/issues/173 by making the selected language reflected in the URL. Resolving in favor of https://github.com/CatalystCode/project-fortis-pipeline/issues/173.
