### ISSUE TITLE
Term Filters: language inconsistent

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#217]
* open site
* change language to en
* type gunfire in filter list and wait for UI to change

Top 5 terms still has some, but not all Spanish items:

![image](https://user-images.githubusercontent.com/8771377/32550143-07f7fdb4-c45a-11e7-9913-4caf4f2e4a8c.png)

**Comment by erikschlegel** [comment]
we should just remove the Top 5 terms and Other Terms options from the list

**Comment by c-w** [comment]
Resolving as duplicate of #192 since the "top terms" is now removed.
