### ISSUE TITLE
No Facts Loading

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#220]
* open http://fortis-portal.52.167.224.142.nip.io/#/site/armedconflict/facts/
* click on Facts

Page stuck on "Loading facts...". No error message. F12 looks fine

![image](https://user-images.githubusercontent.com/8771377/32550600-b892f308-c45b-11e7-8b98-10179f519642.png)

**Comment by c-w** [comment]
There are a bunch of PRs to implement this:
- https://github.com/CatalystCode/project-fortis-pipeline/pull/165
- https://github.com/CatalystCode/project-fortis-interfaces/pull/101
- https://github.com/CatalystCode/project-fortis-services/pull/163

**Comment by c-w** [comment]
All the PRs are merged so a MVP facts view should now be implemented.
