### ISSUE TITLE
Reminder: Pentest

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#223]
Shouldn't be a big effort since we don't have a lot of user input, but still important to pen test UI and API tier since we're storing sensitive information.

**Comment by anthturner** [comment]
Accepted, pending the setup of a functional development instance, per @c-w

**Comment by c-w** [comment]
This task is blocked on https://github.com/CatalystCode/project-fortis-pipeline/issues/176 and https://github.com/CatalystCode/project-fortis-pipeline/issues/243 -- let's first implement at least basic auth and ssl before we take a wrench to this.

**Comment by c-w** [comment]
Resolving this in favor of #222 so that we have a single item to track all outcomes of the security review.
