### ISSUE TITLE
VM size dropdown not region specific

### ISSUE THREAD

**Issue by c-w** [CatalystCode/fortisdeploy#229]
Deployments seem to fail with cryptic error messages:

![image](https://user-images.githubusercontent.com/1086421/33281072-02584806-d372-11e7-9a1c-2360f45a1dfc.png)

Digging deeper shows that the VM sizes in the deployment dropdown are not region specific

![image](https://user-images.githubusercontent.com/1086421/33281100-15008202-d372-11e7-9dbb-a80a21052f80.png)

Suggestion: the VM size dropdown should only contain instances that are (a) compatible with the Cassandra Helm Chart and (b) available in the region.

**Comment by NathanielRose** [comment]
#230 Related Issue.
*In Progress*
Azure L Series currently available:
-  East US 2
- West US
- Canada Central
- Canada East
- Australia East

Question: @c-w  Should we only light up the supported VM sizes that are specific to these regions?

**Comment by c-w** [comment]
@NathanielRose https://github.com/CatalystCode/project-fortis-pipeline/issues/172 removed the requirement for L series to be available in the region to which the pipeline is deployed (I hope); as such, it should be fine if the VM size dropdown just lists all the SKUs that have SSDs that are available in the region.

**Comment by c-w** [comment]
This may help https://stackoverflow.com/a/35545678

**Comment by NathanielRose** [comment]
Update - ATM there isn't really a method to dynamically set allowedValues. Using an object for the parameter just let's you pass in more complex data. Only way to set the allowedValues is by a hard coded static array in the template.
- https://docs.microsoft.com/en-us/azure/architecture/building-blocks/extending-templates/collector
- https://docs.microsoft.com/en-us/azure/architecture/building-blocks/extending-templates/objects-as-parameters
- https://stackoverflow.com/questions/44643329/can-i-dynamically-generate-parameters-in-azure-templates

Currently looking to see if PM team can work with us to support this: https://www.yammer.com/microsoft.com/threads/995013259

**Comment by c-w** [comment]
Closing this off since it's not currently possible to implement this. Let me know if you get input from the product team and we can re-open this.

**Comment by NathanielRose** [comment]
If we build the template into a managed application, we can leverage the UI definition to handle this for you. Up to the team to see if they'd want to explore that route.
