### ISSUE TITLE
Unable to specify region in ARM deployment

### ISSUE THREAD

**Issue by c-w** [CatalystCode/fortisdeploy#230]
Currently it's impossible to specify the Azure location for a new deployment.

![screencapture-deploy-azure-1511806404719](https://user-images.githubusercontent.com/1086421/33281913-df617162-d374-11e7-93d5-6fdc4ca7a74e.png)

This should be an option, e.g. so that we can deploy Fortis to US-East-2 to get access to the L-series VMs which we use for Cassandra.

**Comment by NathanielRose** [comment]
@c-w & @erikschlegel 
Can you test this AzureDeploy button in the [test branch](https://github.com/CatalystCode/project-fortis-pipeline/tree/siteLocation-AzureDeploy)  to see if you can successfully select a Resource Group location on your side as well. If it works, then this is good to be closed.

![image](https://user-images.githubusercontent.com/8294326/33580268-599f32c0-d901-11e7-8f53-d7b6dd5c0065.png)

**Comment by c-w** [comment]
@NathanielRose The deployment scripts in this repo are not reliable so I added your changes to project-fortis-mono for testing https://github.com/CatalystCode/project-fortis-mono/commit/e43784519841f2286f577b36ff0e55cd71953dd7. Trying it out now.

**Comment by c-w** [comment]
Now deploying this:

![image](https://user-images.githubusercontent.com/1086421/33612189-cc02aaca-d99e-11e7-8d4a-6895ca81754f.png)

**Comment by c-w** [comment]
Worked. Resolving. Thanks for the commit, @NathanielRose.
