### ISSUE TITLE
deploying production cluster to WestUS2 resulting in error during ACS cluster bring up

### ISSUE THREAD

**Issue by jmspring** [CatalystCode/fortisdeploy#250]
"deploysite" target failing.  See attached screen shots since cut and paste from the portal didn't work.

<img width="365" alt="screen shot 2018-01-17 at 10 58 20 am" src="https://user-images.githubusercontent.com/124302/35065176-4c2775d8-fb81-11e7-9b4a-d7fd92eafc86.png">
<img width="347" alt="screen shot 2018-01-17 at 10 58 30 am" src="https://user-images.githubusercontent.com/124302/35065177-4c6c7296-fb81-11e7-8b94-691cb96fc7c2.png">
<img width="345" alt="screen shot 2018-01-17 at 10 58 39 am" src="https://user-images.githubusercontent.com/124302/35065178-4c8a10bc-fb81-11e7-9653-9ed90209856d.png">

**Comment by c-w** [comment]
The code that throws the error is this part of the [setup_k8_cluster](https://github.com/CatalystCode/project-fortis/blob/36005f739b7a159c1a8c5842c24cbbabdc41275b/project-fortis-pipeline/fortis-deploy.sh#L190-L219) method:

```sh
  master_vm_ids=$(az vm list -g "${resource_group}" --query "[].id" -o tsv | grep "${resource_group}" | grep "k8s-master-")
  echo "Master VM ids: ${master_vm_ids}"

  # ERROR here because the --ids argument is empty!
  az vm user update -u "${temp_user_name}" --ssh-key-value "${temp_pub_key}" --ids "${master_vm_ids}"
```

Given that the error doesn't always occur, I hypothesize that there is a race condition here where the VM ids haven't been assigned yet at the time they're being queried, whence we get an empty argument warning for the `--ids` argument to the `az vm user create` call.

**Comment by c-w** [comment]
To fix the potential race condition identified above, I added a wait for the k8s-master in https://github.com/CatalystCode/project-fortis/commit/dda91136a0b4761e6844f3c62cf0fb08a878aad5. Please let me know if you still experience this issue.

**Comment by c-w** [comment]
Resolving; please re-open if you experience this again.
