### ISSUE TITLE
deployment to West US 2 and L4s VMs repeatedly fails

### ISSUE THREAD

**Issue by jmspring** [CatalystCode/fortisdeploy#251]
I've attempted multiple deployments to West US2 with L4s VMs, each deployment has failed with timeouts.  The error from the deployment:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningTimeout\",\r\n \"message\": \"Provisioning of VM extension 'deploysite' has timed out. Extension installation may be taking too long, or extension status could not be obtained.\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by jmspring** [comment]
The issue is likely that West US2 uses ACS RPv2 where East US does not.  This is shown in the way ACS provisions a separate resource group for ACS resources.  See attached screenshot.

<img width="721" alt="screen shot 2018-01-22 at 8 09 29 pm" src="https://user-images.githubusercontent.com/124302/35257804-5a4357a8-ffb0-11e7-897f-c65ba7c2eef3.png">

**Comment by c-w** [comment]
Do we have a list of regions that run RPv2? Are we expecting to move to RPv2 across all data-centers in the future?

**Comment by jmspring** [comment]
RPv2 on ACS is in the following regions:

Canada Central, Canada East, Central India, Japan West, South India, UK
South, UK West, West Central US, West India, West US 2

RPv2 will not be rolled out to other regions.

**Comment by c-w** [comment]
In that case, I'd suggest we just remove those regions from the `siteLocations` list in [azuredeploy.json](https://github.com/CatalystCode/project-fortis/blob/62b72810781ae65803398b0f203407649588e6bb/azuredeploy.json#L11-L44). Great find by the way!

**Comment by jmspring** [comment]
That would be the most expedient approach.  Will do so in the AM.

**Comment by jmspring** [comment]
Closed via PR into project-fortis.
