### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by c-w** [CatalystCode/fortisdeploy#253]
We have three top-level documentation areas:

- [Find out more about the project](https://github.com/CatalystCode/project-fortis/blob/master/project-fortis-pipeline/docs/background.md)
- [Learn how to set up Fortis in Azure](https://github.com/CatalystCode/project-fortis/blob/master/project-fortis-pipeline/docs/production-setup.md)
- [Onboarding guide for developers](https://github.com/CatalystCode/project-fortis/blob/master/project-fortis-pipeline/docs/development-setup.md)

The first two are user-facing, the last one is for developers. We should ensure that all of these documents are as clear as possible (with the user-facing ones getting priority).

E.g. to double check the deployment guide, it would be good for someone with less familiarity with Fortis to set up a site and record all the gaps in the guide so that we can fix them.

**Comment by rachelnicole** [comment]
I'm going to be creating suggested additions to each section in the format of a checklist, with deeper explanation of why I think it's helpful below. 

- [Find Out More About the Project](https://github.com/CatalystCode/project-fortis/blob/master/project-fortis-pipeline/docs/background.md)
- [Learn How to Set Up Fortis in Azure](https://github.com/CatalystCode/project-fortis/blob/master/project-fortis-pipeline/docs/production-setup.md)
  - [ ] Explain briefly what Azure is and why you would need the subscription
  - [ ] Explain what a TLS certificate is
  - [ ] Explain what Mapbox is and why we're using it
- [Onboarding Guide for Developers](https://github.com/CatalystCode/project-fortis/blob/master/project-fortis-pipeline/docs/development-setup.md)
  - [ ] Add a 'known Docker issues' section, talk about how it sometimes stalls out on Windows and how to fix that.
  - [ ] Add a common errors section to talk about what to do to your production environment when you see certain things (like the GraphQL error for bad schema)
  - [ ] Add a section (maybe a link to a new .md file) perhaps explaining what libraries we're using for certain things and why (like the leaflet-map react library), with links to examples of its use in the code.

**Comment by Smarker** [comment]
I'll make a PR and add comments for these:

* [Production Setup](https://github.com/CatalystCode/project-fortis/blob/master/project-fortis-pipeline/docs/production-setup.md)
    - [x] It'd help to have a **table** of all the fields (with descriptions or links) you will see in deploy to azure to make sure that you know to take note of fields when you are creating an AD app, service principal, etc.
   - [x] What to put as `Fortis Site Clone Url`
   - [x] Take note that you need to save your `AD Client Id` ([ad client id resource](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal#get-application-id-and-authentication-key) `Copy the Application ID and store it in your application code. Some sample applications refer to this value as the client ID.`)
   - [x] Specify that to create AD app and assign it a role, you need **owner** or **user access admin role**
    - [ ] I think we use `Event Hub` as user-facing to serve for `TadaWeb`, so this needs to be updated in the **trusted sources** section of admin
   - [x] Fortis users and admins should be specified in what format? email? - If I specify myself as an admin, must I also specify myself as a user? - no the deployment will do it for you
   - [x] Need more explanation on the format expected for ingress hostname

**Comment by Smarker** [comment]
PR for Production Setup Deployment Parameters Table: https://github.com/CatalystCode/project-fortis/pull/24

**Comment by c-w** [comment]
Add a new end-to-end diagram that should contain all the moving pieces in Fortis: https://github.com/CatalystCode/project-fortis/blob/master/project-fortis-pipeline/docs/development-setup.md#architecture-overview
