### ISSUE TITLE
Expose the Spark UI

### ISSUE THREAD

**Issue by Smarker** [CatalystCode/fortisdeploy#257]
When a site is deployed in production, there is no way to access the spark ui. (currently we are using `nginx ingress`)

Clemens said that the ui could be accessed either from the deployment vm or by adding a temporary public ip for the spark ui.

Jim Spring would know how to expose the spark ui. (The ui can be found through the service spark-master when running `kubectl get svc -n spark`)

Once the spark ui is exposed, provide documentation on this.

**Comment by c-w** [comment]
This is now documented at https://github.com/CatalystCode/project-fortis/blob/master/project-fortis-pipeline/docs/development-setup.md#debugging-production-spark-issues

**Comment by Smarker** [comment]
The link above didn't bring me to debugging spark issues but I found it here: https://github.com/CatalystCode/project-fortis/blob/master/project-fortis-pipeline/docs/development-faq.md#how-do-i-debug-issues-with-the-production-spark-job

**Comment by c-w** [comment]
Yes, I split out the FAQ into its own file after resolving this issue since it was getting a pretty long document. Thanks for the updated link.
